### ISSUE TITLE
Media image selection in tx_news 9.11 is broken

### ISSUE THREAD

**Issue by casimainz** [buepro/typo3-pizpalue#18]
Using typo3 11.5.5
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1351584844: An argument "key" or "id" has to be provided | TYPO3Fluid\Fluid\Core\ViewHelper\Exception thrown in file .../typo3_src-11.5.5/typo3/sysext/fluid/Classes/ViewHelpers/TranslateViewHelper.php in line 148.

**Comment by casimainz** [comment]
The issue might be in 
/TCA/Overrides/500_cropping.php

**Comment by Manawyrm** [comment]
Hi!

We're using 12.1.0 (which should include this fix), but the error still occurs.
The files changed in the bugfix commit are correctly changed on our installation.

Any idea why this might still happen?
(using Typo3 11.5.7, pizpalue 12.1.0, PHP 8.0)
Thanks!

**Comment by buepro** [comment]
Hi @Manawyrm, thank you for reporting. The issue should be fixed now. For your installation you might download the latest commit from the [BP-12.0 branch](https://github.com/buepro/typo3-pizpalue/tree/BP-12.0).

**Comment by Manawyrm** [comment]
Hello @buepro ,
awesome, thank you very much for the quick fix, it works now :smile: 

Thanks!
