### ISSUE TITLE
news system and modal not in german

### ISSUE THREAD

**Issue by schorsch8878** [buepro/typo3-pizpalue#2]
Hello, 

I installed pizpalue in a new Typo3 10.4.6, everything is allright. But in the news the "read more" an in modal the "close" links are in english. I configured the site config to german. 

I use this Versions: 

news 8.3.0

pizpalue 11.2.0

bootstrap_package 11.0.2

Can you help me?

Thank you

**Comment by buepro** [comment]
Hi, did you add German in the "Manage Language Packs"-Dialog from the maintenance module?

![grafik](https://user-images.githubusercontent.com/37214997/90410544-c86efb00-e0aa-11ea-9540-8b0df1660aab.png)

![ManageLanguagePacks](https://user-images.githubusercontent.com/37214997/90410619-e3da0600-e0aa-11ea-9d6b-b3e17614e02f.jpg)

![grafik](https://user-images.githubusercontent.com/37214997/90410723-01a76b00-e0ab-11ea-9ed8-dffdb8589083.png)

**Comment by schorsch8878** [comment]
Hey, oh, sorry! (Brett vor dem Kopf)

Many Thanks!
