### ISSUE TITLE
PHP Warning: Undefined array key "title"

### ISSUE THREAD

**Issue by ste101** [buepro/typo3-pizpalue#34]
When clicking at in a folder page (TYPO3 11.5.24) at 'Create new record' I'm getting the error
`PHP Warning: Undefined array key "title" in xxx/typo3_src-11.5.24/typo3/sysext/backend/Classes/Controller/NewRecordController.php line 529`
The trigger is file 610_ext_easyconf_init.php in version 14.2.1.
I don't think that this line is correct:
`if (!\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::isLoaded('easyconf')) {`
because it should load if easyconf is loaded.
Also the line 25 outside the if command is wrong.

File 600_ext_easyconf.php in main seams to have the same problem.

**Comment by buepro** [comment]
The ctrl section has been introduced to fix issues related to easyconf being installed after pizpalue.
