### ISSUE TITLE
Unable to get property "type" of non-object "getTSFE()" error when accessing easyconfig, log and Extensions.

### ISSUE THREAD

**Issue by JavierVelazquez** [buepro/typo3-pizpalue#40]
Hello all, when accessing some items in the backend (for example extensions or Log) I get the following error: Unable to get property "type" of non-object "getTSFE()" not on others. typo3 v12.4.1 pretty clean install in a remote server with pizpalue extension. Maintenance, Settings, Upgrade... load with no problem. The configuration of pizpalue (its own easyconfig) gets the error too.
Any ideas?

**Comment by JavierVelazquez** [comment]
Solved! Pizpalue had to be last in the "Include Typoscrip sets"!! Silly...

**Comment by buepro** [comment]
Thank you for this information.
