### ISSUE TITLE
Use %d. %B %Y as dateformat for news template

### ISSUE THREAD

**Issue by ste101** [buepro/typo3-pizpalue#46]
In news partial AdditionalInformation.html uses `j. F Y` for date formating.
Unfortunatelly with this configuration the name of the month isn't translated.
Please use `%d. %B %Y` instead.

Unfortunatelly I didn't find the place to change this.

**Comment by buepro** [comment]
This configuration has been moved to the site package. Please adjust it in this way:
```
plugin {
    tx_news {
        _LOCAL_LANG {
            default {
                dateFormat = %d. %B %Y
                // or dateFormat = {$pizpalue.general.dateStrftimeFormat}
            }
            de {
                dateFormat = %d. %B %Y
                // or dateFormat = {$pizpalue.general.dateStrftimeFormat}
            }
        }
    }
}
```
