### ISSUE TITLE
Can't edit content element T3 12.4.8 and Piz 15.2.0

### ISSUE THREAD

**Issue by Busfreak** [buepro/typo3-pizpalue#47]
Hi :-)
I Have installed a fresh TYPO3 12.4.8 and got the actual Pizpalue distribution, 15.2.0.
Configuration works well, but I can't edit a content element. I get the error:
str_contains(): Argument #1 ($haystack) must be of type string, int given | TypeError thrown in file /www/htdocs/w01e9844/pitz.kompass-bildung.de/typo3_src-12.4.8/typo3/sysext/core/Classes/Configuration/CKEditor5Migrator.php in line 766.

I Have installed version 16.0.0 from github. This solved the problem editing content elements, but now other things don't work like the top-menu.

Do you have any suggestions for me?
THX!!

**Comment by buepro** [comment]
The upcoming release requires as well the latest bootstrap_package having a different main menu. If you like to work with an earlier version you could apply the fix from commit [#b9dfb4a](https://github.com/buepro/typo3-pizpalue/commit/b9dfb4a3e4deb50ea691b00b6564839194936be4).

**Comment by Busfreak** [comment]
Thank you very much! That helped :-)
